#!/bin/bash
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
apt-get update && echo 'y' | apt-get upgrade
apt-get install cron
apt-get install dos2unix
cd /opt/  || exit
wget http://dl.4players.de/ts/releases/3.0.13.6/teamspeak3-server_linux_amd64-3.0.13.6.tar.bz2
sleep 2
tar -jxvf teamspeak3-server_linux_amd64-3.0.13.6.tar.bz2
mv /opt/teamspeak3-server_linux_amd64 /opt/teamspeak
chown -R root:root /opt/teamspeak
cd /opt/teamspeak  || exit
./ts3server_startscript.sh start
sleep 10
./ts3server_startscript.sh stop
sleep 5
rm /opt/teamspeak/query_ip_whitelist.txt
wget https://raw.githubusercontent.com/Naspyy/teamspeak-installer/master/query_ip_whitelist.txt
mv query_ip_whitelist.txt /opt/teamspeak/query_ip_whitelist.txt
chmod 755 /opt/teamspeak/query_ip_whitelist.txt
sleep 1
cd /opt/teamspeak/  || exit
./ts3server_startscript.sh start
sleep 5
wget https://raw.githubusercontent.com/Naspyy/teamspeak-installer/master/anticrash.sh
mv anticrash.sh /opt/teamspeak/anticrash.sh
dos2unix /opt/teamspeak/anticrash.sh
cd /opt/teamspeak/logs/  || exit
echo > anticrash.txt
chmod 777 anticrash.txt
crontab -l | { cat; echo "* * * * * cd /opt/teamspeak && ./anticrash.sh > /opt/teamspeak/logs/anticrash.txt"; } | crontab -
chmod 755 /opt/teamspeak/anticrash.sh
chown -R root:root /opt/teamspeak
