#!/bin/bash
# enable IPv6 support
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
# update and install needed dependencies
apt-get update && echo 'y'
apt-get -y install sudo cron dos2unix nano zip unzip
# create, download, extract and rename teamspeak-directory
adduser --disabled-password --no-create-home --gecos "" teamspeak
mkdir /opt/teamspeak
chown -R teamspeak:teamspeak /opt/teamspeak
cd /opt/teamspeak || exit
wget http://teamspeak.gameserver.gamed.de/ts3/releases/3.0.13.6/teamspeak3-server_linux_amd64-3.0.13.6.tar.bz2
tar -jxvf teamspeak3-server_linux*.tar.bz2
mv teamspeak3-server_linux_amd64 server
rm teamspeak3-server_linux*.tar.bz2
chown -R teamspeak:teamspeak /opt/teamspeak
# start teamspeak for the first time
cd /opt/teamspeak || exit
wget https://github.com/Naspyy/teamspeak-installer/raw/master/run-as-teamspeak-user.sh
chmod +x backup.sh
dos2unix /opt/teamspeak/run-as-teamspeak-user.sh
chown -R teamspeak:teamspeak /opt/teamspeak/run-as-teamspeak-user.sh
chmod +x /opt/teamspeak/run-as-teamspeak-user.sh
su -s /bin/bash -c '/opt/teamspeak/run-as-teamspeak-user.sh' teamspeak
